# Generated by Django 3.2.2 on 2021-05-17 08:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description_short', models.CharField(default='Project Description', max_length=200)),
                ('description_long', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ImageField(default='project.png', upload_to='covers/')),
                ('description_alt', models.CharField(default='Project Alt Description', max_length=100)),
            ],
        ),
    ]
