# Generated by Django 3.2.2 on 2021-05-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover",
            field=models.ImageField(default="project.png", upload_to="covers/"),
        ),
    ]
