name: Push
on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    name: build test
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
      CLOUD_API_KEY: ${{ secrets.CLOUD_API_KEY }}
      CLOUD_API_SECRET: ${{ secrets.CLOUD_API_SECRET }}

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker
        run: docker-compose build --build-arg CLOUD_NAME=${{ secrets.CLOUD_NAME }}
      - name: Run Docker
        run: docker-compose up -d
      - name: Check running containers
        run: docker-compose ps -a
      - name: Check logs
        run: docker-compose logs web
      - name: Make migrations
        run: docker-compose exec web python manage.py makemigrations
      - name: Migrate tables
        run: docker-compose exec web python manage.py migrate
      - name: Run tests
        run: docker-compose exec -T web pytest -p no:warnings --cov=.

  code-quality:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 bandit safety
      - name: Run black
        run: black app/. --check
      - name: Run isort
        run: isort --profile black app/. --check-only
      - name: Run flake8
        run: flake8 app/. --config=app/.flake8
      - name: Run bandit
        run: bandit app/.
      - name: Run safety
        run: safety check

  build:
    runs-on: ubuntu-latest
    name: build prod
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
      CLOUD_API_KEY: ${{ secrets.CLOUD_API_KEY }}
      CLOUD_API_SECRET: ${{ secrets.CLOUD_API_SECRET }}

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker
        run: docker-compose build -f docker-compose-prod.yml --build-arg CLOUD_NAME=${{ secrets.CLOUD_NAME }}
      - name: Run Docker
        run: docker-compose up -d
      - name: Check running containers
        run: docker-compose ps -a
      - name: Check logs
        run: docker-compose logs web